export const protectedHosts: string[] = [
	'acgnx.se',
	'bit.ly',
	'cdn.filezilla-project.org',
	'digitaloceanspaces.com',
	'facebook.com',
	'ggpht.com',
	'github.com',
	'githubusercontent.com',
	'google.com',
	'google.com.sg',
	'google.com.hk',
	'googleapis.com',
	'googleusercontent.com',
	'googlevideo.com',
	'gravatar.com',
	'gstatic.com',
	'instagram.com',
	'linkedin.com',
	'kamigami.org',
	'nyaa.si',
	'paypalobjects.com',
	'pixiv.net',
	'qbittorrent.org',
	'quora.com',
	'sstatic.net',
	'stackoverflow.com',
	'tw',
	'twitter.com',
	'twimg.com',
	'wikimedia.org',
	'wikipedia.org',
	'youtube.com',
	'ytimg.com',
];

export const proxy = 'PROXY localhost:1080;';

export const direct = 'DIRECT;';
