export const protectedHosts: string[] = [
	'amazon.co.jp',
	'digitaloceanspaces.com',
	'facebook.com',
	'fbcdn.net',
	'github.com',
	'githubassets.com',
	'githubusercontent.com',
	'google.com',
	'googleapis.com',
	'googleblog.com',
	'googlesource.com',
	'googleusercontent.com',
	'googlevideo.com',
	'gravatar.com',
	'gstatic.com',
	'hub.docker.com',
	'instagram.com',
	'linkedin.com',
	'kamigami.org',
	'mikanani.me',
	'nyaa.si',
	'openai.com',
	'paypalobjects.com',
	'pinterest.com',
	'pixiv.net',
	'qbittorrent.org',
	'quora.com',
	'rakuten.co.jp',
	'sslwidget.criteo.com',
	'sstatic.net',
	'stackoverflow.com',
	'tw',
	'twitter.com',
	'twimg.com',
	'wikimedia.org',
	'wikipedia.org',
	'youtube.com',
	'ytimg.com',
	'52poke.wiki',
];

export const proxy = 'PROXY localhost:1080;';

export const direct = 'DIRECT;';
